### PR TITLE
add musl-linux-* targets, depend on linux-libc-dev

### PR DESCRIPTION
**Pull request by shawnl**

### CODE REVIEW

**Comment by rockstar177** [comment]
I know that this is not so, but I have a question. Can I use this library as a standard C language library for my operating system?
I compiled this library with the option --disabled-shared, linked it to the kernel, but when the call to pritntf () occurs, the bootloader reboots the OS. What can I do to fix this?

**Comment by shawnl** [comment]
On Nov 12, 2017 09:49, "rockstar177" <notifications@github.com> wrote:

I know it's off topic, but I have a question. Can I use this library as a
standard C language library for my operating system?

Yes, but your whole system has to be rebuilt for a diffrnt libc.

I compiled this library with the option --disabled-shared when I linked it
to the kernel, but when the call to pritntf () occurs, the bootloader
reboots the OS. What can I do to fix this?

The kernel has its own libc, and has nothing to do with musl.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wermut/musl/pull/2#issuecomment-343754258>, or mute the
thread

**Comment by rockstar177** [comment]
Yes, but your whole system has to be rebuilt for a diffrnt libc. Host or what? How I can do this?

**Comment by shawnl** [comment]
Use gentoo. It is quite involved, even for someone experienced, and you
will run into problems along the way

**Comment by rockstar177** [comment]
"And you
will run into problems along the way" Maybe "And you will not run into problems along the way."

If so, as I wrote, then I caught the meaning :)

**Pull request closed without merging**
